### ISSUE TITLE
Downloads are pinned to de.archive.ubuntu.com/ubuntu/pool/main

### ISSUE THREAD

**Issue by rob42** [sprylab/ansible-role-tomcat-ubuntu#2]
I want to control the repo I download from, either an internal repo, or another mirror but I cant do it as the repo is hard-coded to de.archive.ubuntu.com

Pls change to use {{tomcat_ubuntu_repo}}, so  tasks/main.yml becomes:

```
- name: Download Tomcat from Ubuntu Package archive
  get_url:
    url: "{{ item }}"
    dest: "{{ tomcat_ubuntu_download_dir }}"
  with_items:
    - http://{{tomcat_ubuntu_repo}}/ubuntu/pool/main/t/tomcat8/tomcat8_{{ tomcat_ubuntu_version }}.deb
        etc....
```
